# Generated by Django 4.1.7 on 2023-03-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_orderitem_ordered_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file_name',
            field=models.CharField(default='img/tee.jpg', max_length=50),
            preserve_default=False,
        ),
    ]
