# Generated by Django 4.1.7 on 2023-03-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_item_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Tops'), ('B', 'Bottoms'), ('O', 'Outwear')], max_length=2),
        ),
    ]
