# Generated by Django 4.1.7 on 2023-03-21 23:55

from django.db import migrations, models
import django_countries.fields
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='1111', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address2',
            field=models.CharField(default='111111', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='DNLCUEVA@HOTMAIL.COM', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='f_name',
            field=models.CharField(default='HAHAH', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='l_name',
            field=models.CharField(default='AHHAHAH', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=localflavor.us.models.USStateField(default='CA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='zip',
            field=localflavor.us.models.USZipCodeField(default='91706', max_length=10),
            preserve_default=False,
        ),
    ]
