# Generated by Django 4.1.7 on 2023-03-22 22:19

from django.db import migrations
import django_countries.fields
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_order_address_alter_order_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='United States of America', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=localflavor.us.models.USStateField(default='CA', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='zip',
            field=localflavor.us.models.USZipCodeField(default='91706', max_length=10),
            preserve_default=False,
        ),
    ]
